### ISSUE TITLE
Going public

### ISSUE THREAD

**Issue by iboB** [alpaca-core/ac-local#150]
This is the public release checklist:

* [x] Rename the discussions category General to Development (as all discussions here are about the development of the software). Create a new category General exactly as this one, but empty.
* [x] Organize dev docs.
* [x] List third party software licenses
* [x] Document directory structure
* [x] Enable CI on push (or at least daily)
* [x] Cross-reference demos in readme
* [x] `git tag -a v0.1.0 -m "Initial public release"`
* [x] make a gh release, write comment that it's just an mvp/alpha and drastic changes are expected, link releases in readme
* [x] update submodules in demos to point to tagged version
* [x] close mvp project and move remaining issues to others
* Make the following repos public:
	* [x] this one, duh
	* [x] https://github.com/alpaca-core/demo-ios-llama-chat
	* [x] https://github.com/alpaca-core/demo-android-ai-chat
	* [x] https://github.com/alpaca-core/mini-reflect
* Make the following projects public:
	* [x] MVP: https://github.com/orgs/alpaca-core/projects/3
	* [x] Beta: https://github.com/orgs/alpaca-core/projects/9
